name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # optional daily update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: AryanAyyu
